### ISSUE TITLE
When does properties for resources are generated?

### ISSUE THREAD

**Issue by mata-r** [krisho007/c_cpe_13_certification#5]
I am following the book instructions, and I don't have properties for the "extnCertification-db" resource in the mta.yaml file.

Repo 
```
resources:
  - name: extnCertification-db
    type: com.sap.xs.hdi-container
    parameters:
      service: hana # or 'hanatrial' on trial landscapes
      service-plan: hdi-shared
    properties:
      hdi-service-name: ${service-name}
```

My application: 

```
resources:
  - name: extnCertification-db
    type: com.sap.xs.hdi-container
    parameters:
      service: hana
      service-plan: hdi-shared
```

What exactly is the property hdi-service-name ?
Please advise
